version: '3.1'

services:
  web:
    build: nginx
    volumes:
    - ./templates:/etc/nginx/templates
    ports:
    - "80:80"
    environment:
    #- NGINX_HOST=foobar.com
    - NGINX_PORT=80
#Wordpres Replication Start
  wordpress1:
    image: wordpress
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html
      
  wordpress2:
    image: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
    volumes:
      - wordpress:/var/www/html
#End Of Wordpress Replication
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
